### PR TITLE
Header changes & Color Updates

### PR DESCRIPTION
**Pull request by Mg138**

### CODE REVIEW

**Comment by m4rch3n1ng** [comment]
ty for the actual dark mode (and the accessibility adjustments), but would it be possible for you to make a separate pr for all the color / misc changes so i can easily merge those changes without merging the flex changes to the header? thx and sorry for being a bit of a hassle.

**Comment by Mg138** [comment]
Bit eh about the flex changes? Would like to split them, but tbh that's kinda difficult and we just did it altogether because we wanted the right bar to work on our initial header changes.

**Comment by Mg138** [comment]
Personally we find the new flex style to be more consistent when resizing (less cranky) and it feels somewhat more fluid.

**Comment by Mg138** [comment]
Oh, it was because our initial changes to the header broke the dark/light mode button's positioning.

I wonder if there's a way to do the collapsing way without media queries?

**Comment by m4rch3n1ng** [comment]
probably not without javascript or media queries, but like, we have the media queries, i am using them everywhere anyways and they are incomprehensibly fast so why not use them? wrapping them into different lines looks pretty cheap, especially if the darkmode toggle wraps first, which is probably unavoidable with the layout i believe to be the most intuitive.

**Comment by m4rch3n1ng** [comment]
unsure exactly where my own commits went, but i have updated to include the two commits i added to main, including build scripst

**Comment by Mg138** [comment]
The media query looked a bit awkward because it didn't actually collapse it at the right width, is all.

**Comment by m4rch3n1ng** [comment]
yeah i made that query in like 10s

**Comment by m4rch3n1ng** [comment]
tysm

**Pull request merged**
